config/routes.rb
Rails.application.routes.draw do
  root 'info#home'
  get 'people_names.json' => 'info#people_names'
  get 'path_between/:name1/:name2.json' => 'info#path_between'

  get 'episodes/:base64_guid' => 'episodes#show', as: :episodes_show
  get 'people/:name' => 'people#show', as: :person_show
end

app/models/artist.rb
class Artist 
  include Neo4j::ActiveNode

  id_property :itunes_id

  property :name
  property :view_url
end

app/models/episode.rb
require "base64"

class Episode 
  include Neo4j::ActiveNode

  id_property :guid
  property :description
  property :itunes_author
  property :link
  property :title

  has_one :in, :show, type: :HAS_EPISODE

  has_many :out, :authors, type: :HAS_AUTHOR, model_class: :Person
  has_many :in, :people_mentioned, type: :MENTIONED_IN, model_class: :Person

  def base64_guid
    self.class.base64_guid(self.guid)
  end

  def self.base64_guid(guid)
    Base64.encode64(guid)
  end

  def self.from_base64_guid(encoded_guid)
    self.find(Base64.decode64(encoded_guid))
  end

  SAFE_TAGS = %w(a b body code col colgroup div em h1 h2 h3 h4 h5 h6 hr html i img li ol p pre span strong table tbody td th thead tr ul)
  SAFE_ATTRIBUTES = %w(id class style)
  def html_safe_description
    white_list_sanitizer = Rails::Html::WhiteListSanitizer.new

    white_list_sanitizer.sanitize(self.description, tags: SAFE_TAGS, attributes: SAFE_ATTRIBUTES).html_safe
  end
end

app/models/genre.rb
class Genre 
  include Neo4j::ActiveNode

  property :itunes_id
  property :name
end

app/models/person.rb
class Person 
  include Neo4j::ActiveNode

  id_property :name
  property :lower_name, index: :exact

  has_many :in, :authored_episodes, type: :HAS_AUTHOR, model_class: :Episode
  has_many :out, :mentioned_in, type: :MENTIONED_IN, model_class: :Episode

  has_many :both, :episodes, type: false, model_class: :Episode

  NAME_CACHE_PATH = Rails.root.join('tmp/cache/person_names')
  NAME_CACHE = ActiveSupport::Cache::FileStore.new(NAME_CACHE_PATH, expires_in: 1.week)

  def self.names_matching(name)
    names = NAME_CACHE.fetch('all_names') do
      Person.as(:person).episodes.query_as(:episode)
        .with('person.name AS name', 'count(episode) AS count').order('count DESC')
        .pluck(:name)
    end

    regexp = Regexp.new(Regexp.escape(name.downcase), 'i')

    names.grep(regexp)
  end
end

app/models/show.rb
class Show 
  include Neo4j::ActiveNode

  id_property :itunes_id

  property :release_date
  property :artwork_url600
  property :artwork_url100
  property :country
  property :name
  property :primary_genre_name
  property :artwork_url60
  property :episode_count
  property :view_url
  property :radio_station_url
  property :explicitness
  property :feed_url
  property :artwork_url30
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def show
    @episode = Episode.from_base64_guid(params[:base64_guid])
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def home
  end

  def people_names
    if params[:query].present?
      render json: Person.names_matching(params[:query]).map { |name| {id: name, text: name} }
    else
      render json: []
    end
  end

  def path_between
    @person1 = Person.all.find(params[:name1])
    @person2 = Person.all.find(params[:name2])

    relationship_types = if params[:only_author] == 'true'
                           'HAS_AUTHOR'
                         else
                           'HAS_AUTHOR|MENTIONED_IN'
                         end
    @query = @person1.query_as(:person1)
      .match_nodes(person2: @person2)
      .match("path=shortestPath((person1)-[:#{relationship_types}*1..12]-(person2:Person))")
      .return('nodes(path) AS nodes, rels(path) AS rels')

    result = nil
    @time_taken = Benchmark.realtime do
      result = @query.dup.to_a[0]
    end
    if result
      nodes, rels = [result.nodes, result.rels]

      @path = nodes.zip(rels).flatten.compact
    end

    render layout: false
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = Person.find(params[:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/episodes/show.html.slim
.ui.text.container
  h1 Episode title: #{@episode.title}

  h2 From show: #{@episode.show.name}

  h2 Description:

  = @episode.html_safe_description

  h2 iTunes author string:

  = @episode.itunes_author

  h2 Link:

  = link_to @episode.link, @episode.link

  h2 Authors:

  .ui.list
  - @episode.authors.each do |person|
    .item
      i.user.icon
      = person.name

  h2 Mentioned:

  .ui.list
  - @episode.people_mentioned.each do |person|
    .item
      i.user.icon
      = person.name

app/views/info/_episodes_by_show.html.slim
- rows = episodes.show(:show).pluck('episode.guid, episode.title, show.name')
- rows_by_show_title = rows.group_by(&:last)

- if rows_by_show_title.size > 0

  .ui.styled.accordion
    - rows_by_show_title.sort_by(&:last).each do |show_name, rows|
      .title
        i.dropdown.icon
        = show_name

      .content
        ul
          - rows.sort_by {|_, title, _| title.gsub(/\d+/) {|i| i.rjust(50, '0') }}.each do |guid, title, _|
            li = link_to title, episodes_show_path(base64_guid: Episode.base64_guid(guid))

- else
  | No episodes

app/views/info/home.html.slim
.ui.inverted.vertical.masthead.center.aligned.segment
  .ui.text.container
    h1.ui.inverted.header Six Degrees of Myke Hurley

    h3 A Podcast network query application using the <a href="http://neo4j.com/">Neo4j Graph Database</a> (<a href="https://github.com/neo4j-examples/six_degrees_of_myke">Source Code</a>)

    h4
      | Inspired by <a href="http://www.relay.fm/cortex/15">Cortex Podcast Episode #15</a>
      |  / 
      | Technical details and caveats on <a href="https://www.reddit.com/r/cortexpodcast/comments/3pcbiy/six_degrees_of_separation/cx6px4u">Reddit</a>

    /javascript:
      var people_names = #{@people_names.to_json.html_safe};


.ui.vertical.stripe.segment
  .ui.middle.aligned.stackable.grid.container
    .row
      h1.ui.centered.header style="width: 100%" Find the degrees of separation between:

    .row
      .ui.divided.grid style="width: 100%"
        .eight.wide.column style="text-align: center"
          select.ui.search.dropdown name="person1"
            option value="" Select the first person
            option selected="selected" Myke Hurley

        .ui.vertical.divider and

        .eight.wide.column style="text-align: center"
          select.ui.search.dropdown name="person2"
            option value="" Select the second person

    .centered.row
      .ui.checkbox
        input type="checkbox" name="only_author"
        label Only authors (not simply mentioned in the episode description)

    .row
      #result style="width: 100%"


coffee:
  person1_select = $('select[name=person1]')
  person2_select = $('select[name=person2]')

  select2_options =
    ajax:
      url: '/people_names.json'
      delay: 150
      data: (params) ->
        query: params.term
      processResults: (data, params) ->
        results: data
      cache: true

  person1_select.select2 select2_options
  person2_select.select2 select2_options

  refresh_results = ->
    $('#result').html('<div class="ui active centered inline large loader"></div>')

    value1 = $('select[name=person1]').val()
    value2 = $('select[name=person2]').val()

    if value1.length > 0 and value2.length > 0
      $.get("/path_between/#{value1}/#{value2}.json?only_author=" + $('input[name=only_author]')[0].checked)
        .done (result) ->
          $('#result').html(result)
        .fail ->
          $('#result').html('There was an error with your query')

  $('select').change refresh_results
  $('input').change refresh_results

app/views/info/path_between.html.slim
p Neo4j query used:
pre
  = @query.to_cypher(pretty: true).gsub(/\033\[[0-9;]*m/, '')

p Time taken: #{(@time_taken.to_f * 1000).round(1)}ms

.ui.grid
  - [@person1, @person2].each do |person|
    .five.wide.column
      = render partial: 'people/profile', locals: {person: person}

  .six.wide.column
    - if @path
      - person = @path.shift

      h2
        i.user.icon
        = link_to person.name, person_show_path(person)

      - while @path.present?
        - rel1 = @path.shift
        - episode = @path.shift
        - rel2 = @path.shift
        - person = @path.shift

        - case rel1.rel_type
        - when :HAS_AUTHOR
          h3 = 'Authored'
        - when :MENTIONED_IN
          h3 = 'Mentioned in'

        p
          strong Show: 
          = episode.show.name
        p
          strong Episode title: 
          = link_to episode.title, episodes_show_path(base64_guid: episode.base64_guid)

        - case rel2.rel_type
        - when :HAS_AUTHOR
          h3 = 'Authored by'
        - when :MENTIONED_IN
          h3 = 'Mentioned'

        h2
          i.user.icon
          = link_to person.name, person_show_path(person)

    - else
      p No path within six hops found between #{@person1.name} and #{@person2.name}

coffee:
  $('.ui.accordion').accordion()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Six Degrees Of Myke Hurley</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_profile.html.slim
h1 = person.name

h2 Authored:

= render partial: '/info/episodes_by_show', locals: {episodes: person.authored_episodes(:episode)}

h2 Mentioned in:

= render partial: '/info/episodes_by_show', locals: {episodes: person.mentioned_in(:episode)}

app/views/people/show.html.slim
.ui.text.container
  = render partial: 'profile', locals: {person: @person}

  coffee:
    $('.ui.accordion').accordion()